version: '3.1'

services:
  db:
    image: mysql:5.7.21
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tdd
      MYSQL_USER: tdd
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes: 
      - ./datadir:/var/lib/mysql
     healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy